/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author YASHU
 */
public class GamePage extends javax.swing.JFrame {

   //declaring objects for game page
    Deck d = new Deck();
   //object inilialized for the player as "p"
    Hand p = new  Hand();
   //object intialized for the dealer as "d1"
    Hand d1 = new Hand();
    Integer bet ;
    
    
    
    
    public GamePage() {
        
        initComponents();        
        
        d.shuffle();
                
        p.addCardToHand(d.draw());
        pCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+p.lastCard().getSuit1()+"/"+p.lastCard().getValue1()+".png")));
        d1.addCardToHand(d.draw());
        dCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+d1.lastCard().getSuit1()+"/"+d1.lastCard().getValue1()+".png")));
        p.addCardToHand(d.draw());
        pCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+p.lastCard().getSuit1()+"/"+p.lastCard().getValue1()+".png")));
                
    }
    
    public void setBet(String s)
    {
        this.bet = Integer.parseInt(s);
        PlayerAccount.setText(bet.toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        pCard4 = new javax.swing.JLabel();
        pCard3 = new javax.swing.JLabel();
        pCard2 = new javax.swing.JLabel();
        pCard1 = new javax.swing.JLabel();
        dCard4 = new javax.swing.JLabel();
        dCard3 = new javax.swing.JLabel();
        dCard2 = new javax.swing.JLabel();
        dCard1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PlayerAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("QUIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 110, 50));

        pCard4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 80, 100));

        pCard3.setForeground(new java.awt.Color(255, 255, 255));
        pCard3.setMaximumSize(new java.awt.Dimension(18, 14));
        pCard3.setMinimumSize(new java.awt.Dimension(18, 14));
        pCard3.setPreferredSize(new java.awt.Dimension(18, 14));
        getContentPane().add(pCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 80, 100));

        pCard2.setForeground(new java.awt.Color(255, 255, 255));
        pCard2.setToolTipText("");
        getContentPane().add(pCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 80, 100));

        pCard1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 80, 100));

        dCard4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 64, 70, 90));

        dCard3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 64, 70, 90));

        dCard2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 64, 70, 90));

        dCard1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 64, 70, 90));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Hit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Stand");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 290, 110, 50));

        PlayerAccount.setBackground(new java.awt.Color(255, 255, 0));
        PlayerAccount.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        PlayerAccount.setForeground(new java.awt.Color(255, 255, 255));
        PlayerAccount.setText("user's Account");
        getContentPane().add(PlayerAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 170, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LEVEL 2 PAGE.jpg"))); // NOI18N
        jLabel1.setText("4");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        do
        {
            if(d1.getHandValue() >=17)
                break;
            
          d1.addCardToHand(d.draw());
          
        if(d1.getNumberOfCards()==2)
        dCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+d1.lastCard().getSuit1()+"/"+d1.lastCard().getValue1()+".png")));
        else if(d1.getNumberOfCards()==3)
        dCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+d1.lastCard().getSuit1()+"/"+d1.lastCard().getValue1()+".png")));
        else if(d1.getNumberOfCards()==4)
        dCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+d1.lastCard().getSuit1()+"/"+d1.lastCard().getValue1()+".png")));
            
          
        } while(d1.getNumberOfCards() <= 4);
        
        if(d1.getHandValue()>21 && p.getHandValue()>21)
        {
            
            Push p = new Push();
            p.setVisible(true);
        }
        else if(d1.getHandValue() == p.getHandValue())
        {
            Push p = new Push();
            p.setVisible(true);
        }
        else if(d1.getHandValue() > p.getHandValue())
        {
            Lose l = new Lose();
            l.setVisible(true);            
        }
        else if(p.getHandValue() > d1.getHandValue() )
        {
            Win w = new Win();
            w.setVisible(true);   
        }    
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        p.addCardToHand(d.draw());
        System.out.println(p.getHandValue());
        
        if(p.getNumberOfCards()==3)
        pCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+p.lastCard().getSuit1()+"/"+p.lastCard().getValue1()+".png")));
        else if(p.getNumberOfCards()==4)
        pCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+p.lastCard().getSuit1()+"/"+p.lastCard().getValue1()+".png")));
        
        
        
        
        if(p.getHandValue()>21)
        {
            Lose l = new Lose();
            l.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerAccount;
    private javax.swing.JLabel dCard1;
    private javax.swing.JLabel dCard2;
    private javax.swing.JLabel dCard3;
    private javax.swing.JLabel dCard4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pCard1;
    private javax.swing.JLabel pCard2;
    private javax.swing.JLabel pCard3;
    private javax.swing.JLabel pCard4;
    // End of variables declaration//GEN-END:variables
}
